if (MSVC)
    add_compile_options(/W4 /permissive- /EHsc)
    message(STATUS "[COMPILER] MSVC configuration loaded")
else()
    add_compile_options(-Wall -Wextra -Wpedantic -Werror=return-type)
    if (CMAKE_BUILD_TYPE STREQUAL "Debug")
        add_compile_options(-O0 -g)
    else()
        add_compile_options(-O2)
    endif()
    message(STATUS "[COMPILER] GCC/Clang configuration loaded")
endif()