if (WIN32)
    add_compile_definitions(RF_PLATFORM_WINDOWS)
    message(STATUS "[PLATFORM] Windows detected")
elseif (APPLE)
    add_compile_definitions(RF_PLATFORM_MAC)
    message(STATUS "[PLATFORM] macOS detected")
elseif (UNIX)
    add_compile_definitions(RF_PLATFORM_LINUX)
    message(STATUS "[PLATFORM] Linux detected")
endif()
